### ISSUE TITLE
TOC eat digit

### ISSUE THREAD

**Issue by HUA-USA** [huntertran/markdown-toc#16]
My Markdown title start with digit. The TOC eat those digit.

Plus, recently, I suddenly have a problem that, when I choose "Auto Markdown TOC: Insert/Update", it automatically insert section numbers to the TOC. 

Before, I also have the problem that the leading digits are eaten. But after I save again, it was corrected. Now, the leading digit are just replaced by the section number.

**Comment by huntertran** [comment]
Can you share a simplified version of your document?
In the meantime, please uncheck the setting `Detect and Auto set section`
![image](https://user-images.githubusercontent.com/4468525/69069698-ed87ed80-09f4-11ea-92b1-4e09d66fb850.png)

**Comment by HUA-USA** [comment]
Change the setting works. Thank you very much!

My document start with a date. For example:

# 2019-11-18 ...

After indexing, the first entry in TOC becomes:

-11-18 ...

If I save again, it was corrected as

2019-11-18

However, if the section number was added, it will always be:

1. -11-18 ...

**Comment by huntertran** [comment]
I will turn off that setting by default in the next beta version. Thank you for using the extension 😄

**Comment by zertrin** [comment]
Hi, just to report that the problem still occurs to me _even when the option is disabled_, and even when updating the TOC after saving.

In my case I have a document where the second and third level of headers start with a date

Here is the result

```markdown
# title

<!-- TOC -->

* [-02](#-02)
    * [-02-24](#-02-24)
    * [-02-25](#-02-25)
    * [-02-26](#-02-26)

<!-- /TOC -->

## 2020-02

### 2020-02-24

lorem ispum

### 2020-02-25

lorem ispum

### 2020-02-26

lorem ispum
```

**Comment by huntertran** [comment]
- Root cause: `REGEXP_HEADER_META` was greedy about the leading digits, so `# 1.1.1` parsed as the section number `1.` plus the title `1` — the rest of the digits were eaten. Once 3.1.0 turned header renumbering on by default the wrong parse was written back into the document. The regex now requires whitespace between a section number and the title, so a heading that is nothing but digits is entirely a title.
- Fixed in commit 4761971
- Verified with test in `test/changelog_version_test.md`
- Published in version 3.1.1
