### ISSUE TITLE
command 'extension.updateMarkdownToc' not found

### ISSUE THREAD

**Issue by bovender** [huntertran/markdown-toc#26]
Would love to use this extension, but it fails with the message `command 'extension.updateMarkdownToc' not found`.

```
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:50:36.977Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-88-generic
```

I previously had the original version by AlanWalk installed, which worked, but had issues with the newlines.

Any ideas?

**Comment by huntertran** [comment]
are you using Linux or Windows?

**Comment by bovender** [comment]
Linux, KDE neon, fully patched.

**Comment by huntertran** [comment]
I believe this bug was fixed in the latest version

**Comment by bovender** [comment]
Still doesn't work here. The debug console shows this:

```
[2020-03-28 08:34:55.509] [exthost] [error] Activating extension huntertran.auto-markdown-toc failed due to an error:
[2020-03-28 08:34:55.537] [exthost] [error] Error: Cannot find module './ConfigManager'
Require stack:
- /home/USER/.vscode/extensions/huntertran.auto-markdown-toc-3.0.5/out/AutoMarkdownToc.js
- /home/USER/.vscode/extensions/huntertran.auto-markdown-toc-3.0.5/out/extension.js
- /usr/share/code/resources/app/out/vs/loader.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:849:718)
    at Function.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:819:628)
    at Function.n._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:815:969)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at n (/usr/share/code/resources/app/out/vs/loader.js:15:524)
    at Object.<anonymous> (/home/USER/.vscode/extensions/huntertran.auto-markdown-toc-3.0.5/out/AutoMarkdownToc.js:4:25)
    at Module.o._compile (/usr/share/code/resources/app/out/vs/loader.js:15:749)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:849:718)
    at Function.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:819:628)
    at Function.n._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:815:969)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at n (/usr/share/code/resources/app/out/vs/loader.js:15:524)
    at Object.<anonymous> (/home/USER/.vscode/extensions/huntertran.auto-markdown-toc-3.0.5/out/extension.js:4:27)
    at Module.o._compile (/usr/share/code/resources/app/out/vs/loader.js:15:749)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:849:718)
    at Function.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:819:628)
    at Function.n._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:815:969)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Function.s [as __$__nodeRequire] (/usr/share/code/resources/app/out/vs/loader.js:32:963)
    at d._loadCommonJSModule (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:820:773)
    at d._doActivateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:720:856)
    at d._activateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:719:841)
    at Object.actualActivateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:717:796)
    at d._activateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:522:206)
    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:521:900
    at Array.map (<anonymous>)
    at d._activateExtensions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:521:888)
    at d.activateByEvent (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:519:635)
    at d._activateByEvent (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:718:548)
    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:727:159
```

But thanks for your efforts, I'll keep trying from time to time.

**Comment by huntertran** [comment]
@bovender is it working with version 3.0.11?

**Comment by bovender** [comment]
Yes, thanks, hadn't tried it in a while. Now I was able to insert a TOC at first attempt. Thanks!
